#!/usr/bin/env python3
"""Generate mdioprobe_version.h from version.txt plus git metadata.

Two sources, each answering a different question:

  version.txt   what release this is meant to be. Tracked, bumped by hand.
  git           which build this actually is — `git describe`, plus a dirty
                flag.

`git describe` rather than a bare SHA because it names the build in terms of
the last release rather than as an opaque number. On a tagged commit it is
the tag itself; three commits later it is `v0.1.0-pre-3-gabc1234`, which says
both how far past the release this is and exactly which commit. With no tag
reachable — which is the case on `dev`, since `main` is rebuilt as an orphan
squash and shares no history with it — `--always` falls back to the short
SHA, so nothing is lost where there is nothing to describe.

The previous project also kept a gitignored counter that incremented on
every build. It is not carried over: the file never leaves the machine that
wrote it, so the number means nothing to anyone else, and the SHA already
identifies the build to whoever has the repository.

The header is only rewritten when its contents change, so an unchanged
version does not force a rebuild of everything that includes it.
"""

import argparse
import os
import re
import subprocess
import sys


def read_version(path):
    fields = {}

    with open(path) as source:
        for line in source:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            match = re.fullmatch(r"([A-Z_]+)\s*=\s*(\d+)", line)
            if not match:
                raise SystemExit("{}: cannot parse {!r}".format(path, line))
            fields[match.group(1)] = int(match.group(2))

    missing = {"MAJOR", "MINOR", "PATCH"} - set(fields)
    if missing:
        raise SystemExit("{}: missing {}".format(path, ", ".join(sorted(missing))))
    return fields


def git(root, *args):
    try:
        out = subprocess.check_output(["git", *args], cwd=root,
                                      stderr=subprocess.DEVNULL)
        return out.decode("utf-8", "replace").strip()
    except Exception:
        return None


def git_metadata(root):
    # --tags so lightweight tags count too, --always so a repository with no
    # reachable tag still yields something. The dirty flag stays separate
    # rather than using --dirty: it is also emitted as its own #define, and
    # deriving it from a string suffix would be the wrong way round.
    described = git(root, "describe", "--tags", "--always")

    if not described:
        described = git(root, "rev-parse", "--short", "HEAD") or "unknown"

    status = git(root, "status", "--porcelain")
    return described, bool(status)


def render(fields, described, dirty):
    version = "{}.{}.{}".format(fields["MAJOR"], fields["MINOR"], fields["PATCH"])
    full = "{}+{}{}".format(version, described, "-dirty" if dirty else "")

    return (
        "/* Generated by scripts/gen_version_header.py — do not edit. */\n"
        "#pragma once\n"
        "\n"
        "#define MDIOPROBE_VERSION_MAJOR {}\n".format(fields["MAJOR"]) +
        "#define MDIOPROBE_VERSION_MINOR {}\n".format(fields["MINOR"]) +
        "#define MDIOPROBE_VERSION_PATCH {}\n".format(fields["PATCH"]) +
        "#define MDIOPROBE_VERSION       \"{}\"\n".format(version) +
        "#define MDIOPROBE_GIT_DESCRIBE  \"{}\"\n".format(described) +
        "#define MDIOPROBE_GIT_DIRTY     {}\n".format(1 if dirty else 0) +
        "#define MDIOPROBE_VERSION_FULL  \"{}\"\n".format(full)
    )


def write_if_changed(path, content):
    try:
        with open(path) as existing:
            if existing.read() == content:
                return
    except OSError:
        pass

    os.makedirs(os.path.dirname(path), exist_ok=True)
    tmp = path + ".tmp"
    with open(tmp, "w") as out:
        out.write(content)
    os.replace(tmp, path)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--version-file", required=True)
    ap.add_argument("--out-header", required=True)
    args = ap.parse_args()

    root = os.path.dirname(os.path.abspath(args.version_file)) or "."
    fields = read_version(args.version_file)
    described, dirty = git_metadata(root)

    write_if_changed(args.out_header, render(fields, described, dirty))
    return 0


if __name__ == "__main__":
    sys.exit(main())
